version: "3.8"

services:
  mysql_db:
    image: mysql:8.0.41
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: music_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build: ./server
    container_name: backend_music
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      mysql_db:
        condition: service_healthy
    environment:
      DB_HOST: mysql_db
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: music_db
      PORT: 5000
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build: ./client
    container_name: frontend_music
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  db_data:
